stages:
  - name: Deploy
    inputs:
      - type: git
        branch: main
        dir_name: null
        service: githubconsolidated01
    triggers:
      - type: git
        events: '{"push":true,"pull_request":false,"pull_request_closed":false}'
    permission:
      execute: TOOLCHAIN_ADMINS
    properties:
      - name: DEPLOYER_API_KEY
        type: secure
      - name: RESOURCE_GROUP
        value: Default
        type: text
      - name: ORG
        value: sberajaw@gmail.com
        type: text
      - name: SPACE
        value: dev
        type: text
      - name: ICF_NAMESPACE
        value: poultrysense-bts-ingest
        type: text
      - name: ICF_NAMESPACE_ID
        value: 8adb40c2-ece0-44c8-b03a-15a93a9b631f
        type: text
      - name: POULTRY_SENSE_HOST
        value: http:\/\/ec2-3-226-77-248.compute-1.amazonaws.com:3000
        type: text
      - name: POULTRY_SENSE_USERNAME
        value: Mick@prognostix-poultry.com
        type: text
      - name: POULTRY_SENSE_PASSWORD
        type: secure
      - name: BTS_HOST
        value: food.ibm.com
        type: text
      - name: BTS_ORG_ID
        value: 01d3e95f-b3e5-40b1-835b-cdc13f7ef937
        type: text
      - name: BTS_ORG_PREFIX
        value: "2343234"
        type: text
      - name: BTS_ORG_HQ_GLN
        value: "2343234000001"
        type: text
      - name: BTS_API_KEY
        type: secure
    jobs:
      - name: Build
        type: builder
        curatedDockerImage: default
        artifact_dir: ""
        build_type: shell
        script: "#!/bin/bash\necho \">>> Updating and checking installed version of IBM Cloud CLI…\"\nibmcloud update -f -q\nibmcloud -v\necho \">>> Logging into IBM Cloud…\"\nibmcloud login --apikey $DEPLOYER_API_KEY -r \"us-south\"\nibmcloud target -g $RESOURCE_GROUP\nibmcloud target -o \"$ORG\" -s \"$SPACE\"\necho \">>> Set CLI context to the target namespace:\"\nibmcloud fn property set --namespace $ICF_NAMESPACE\n# echo \">>> Currently Deployed Packages:\"\n# ibmcloud fn package list\n# echo \">>> Currently Deployed Actions:\"\n# ibmcloud fn action list\n# echo \">>> Currently Deployed Triggers:\"\n# ibmcloud fn trigger list\n# echo \">>> Currently Deployed Rules:\"\n# ibmcloud fn rule list\n\nfor d in 01_extractor/ 02_transformer/ 03_loader/ $PWD\ndo\n    if [ -f \"$d/manifest.yaml\" ] \n    then\n        cwd=$(pwd)\n        cd $d && echo \"Processing $d\"\n        echo \">>> Replacing ICF_NAMESPACE_ID In Manifest File…\"\n        sed -i \"s/@ICF_NAMESPACE_ID@/$ICF_NAMESPACE_ID/g\" manifest.yaml\n        echo \">>> Replacing POULTRY_SENSE_HOST In Manifest File…\"\n        sed -i \"s/@POULTRY_SENSE_HOST@/$POULTRY_SENSE_HOST/g\" manifest.yaml\n        echo \">>> Replacing POULTRY_SENSE_USERNAME In Manifest File…\"\n        sed -i \"s/@POULTRY_SENSE_USERNAME@/$POULTRY_SENSE_USERNAME/g\" manifest.yaml\n        echo \">>> Replacing POULTRY_SENSE_PASSWORD In Manifest File…\"\n        sed -i \"s/@POULTRY_SENSE_PASSWORD@/$POULTRY_SENSE_PASSWORD/g\" manifest.yaml\n        echo \">>> Replacing BTS_HOST In Manifest File…\"\n        sed -i \"s/@BTS_HOST@/$BTS_HOST/g\" manifest.yaml\n        echo \">>> Replacing BTS_ORG_ID In Manifest File…\"\n        sed -i \"s/@BTS_ORG_ID@/$BTS_ORG_ID/g\" manifest.yaml\n        echo \">>> Replacing BTS_ORG_PREFIX In Manifest File…\"\n        sed -i \"s/@BTS_ORG_PREFIX@/$BTS_ORG_PREFIX/g\" manifest.yaml\n        echo \">>> Replacing BTS_ORG_HQ_GLN In Manifest File…\"\n        sed -i \"s/@BTS_ORG_HQ_GLN@/$BTS_ORG_HQ_GLN/g\" manifest.yaml\n        echo \">>> Replacing BTS_API_KEY In Manifest File…\"\n        sed -i \"s/@BTS_API_KEY@/$BTS_API_KEY/g\" manifest.yaml\n        echo \">>> Contents Of Manifest File:\"\n        cat manifest.yaml\n        [ -f \"parameters.sh\" ] && source parameters.sh\n        echo \">>> Deploying Artifacts Using IBM Cloud CLI…\"\n        ibmcloud fn deploy -v\n        echo \">>> Successfully Deployed Actions Using IBM Cloud CLI.\"\n        cd $cwd\n    fi\ndone"
properties: []
